const ar = {
    lang: 'اللغة',
    arab: 'عربي',
    next: 'التالي',
    Login: 'تسجيل الدخول',
    email: 'البريد الالكتروني',
    password: 'كلمة المرور',
    forgetPassword: 'هل نسيت دخول كلمة المرور؟',
    entry: 'دخول',
    createAcc: 'سجل الان',
    haveAcc: 'ليس لديك حساب؟',
    haveacco: 'لديك حساب ؟',
    notFile: 'لم يتم اضافه ملف',
    phone: 'رقم الجوال',
    send: 'إرسال',
    RecoverPass: 'استرجاع كلمة المرور',
    confirmPass: 'تآكيد كلمة المرور',
    NewPass: 'كلمة المرور الجديدة',
    confirm: 'تأكيد',
    code: 'كود التحقق',
    Register: 'تسجيل',
    PlanErr: 'يرجي اختيار الخطه ',
    BankErr: 'يرجي اختيار البنك',
    BanknameErr: 'ادخل اسم البنك ',
    AccountnameErr: 'ادخل اسم الحساب',
    AccountnNumberErr: 'ادخل رقم الحساب',
    MoneyPaidErr: 'ادخل المبلغ المسدد',
    BaseErr: 'قم بادراج صورة',
    name: 'الأسم',
    location: 'الموقع الجغرافي',
    wordDownlod: 'تحميل ملف  ورد',
    CodeActive: 'كود التفعيل',
    search: 'بحث',
    HelloApp: 'اهلا في تطبيقنا التعليمي',
    FavLesson: 'ابدأ معنا درسك المفضل',
    lesson: 'دروسي',
    Individualplans: 'الخطط الفردية',
    hours: 'ساعات',
    Rs: 'ريال',
    Lessons: 'درس',
    Home: 'الرئيسية',
    about: 'عن التطبيق',
    Frequentlquestions: 'أسئلة مكررة',
    Termsconditions: 'أحكام وشروط',
    Somthing: 'حدث خطأ ما',
    save: 'إحفظ',
    settings: 'الإعدادات',
    Contact: 'تواصل معنا',
    logout: 'تسجيل خروج',
    notification: 'الأشعارات',
    Firstitem: 'البند الآول',
    seconTerm: 'البند التاني',
    SettApp: 'الأعدادات الخاصة بالتطبيق',
    changePass: 'تغير كلمة المرور',
    NewPassword: 'كلمة المرور الجديدة',
    ContactAp: 'جميع المنصات للتواصل مع التطبيق',
    Social: 'وسائل التواصل',
    sochialMedia: 'وسائل التواصل الاجتماعي',
    sendComplaint: 'ارسال شكوي',
    Subsections: 'الاقسام الفرعية',
    subscribe: 'اشتراك',
    PricePaln: 'خطط الاسعار',
    choosePlane: 'باقة الأشتراك في مجموعه الكورسات المقدمة',
    Monthlyplans: 'الخطط الشهرية',
    completeCours: 'الكورس كامل',
    month: 'شهر',
    throwPlan: 'الخطة الترمية',
    yearPlan: 'الخطة السنوية',
    choosePay: 'اختار وسيلة للدفع',
    Visa: 'فيزا',
    Pay: 'سداد',
    Transfermony: 'حواله بنكيه',
    payment: 'دفع',
    Confirmpayment: 'تأكيد الدفع',
    paymentMony: 'تم دفع الاشتراك في الباقة  بمبلغ ',
    bacjHome: 'العودة للرئيسية',
    myProfile: 'حسابي',
    downloadPdf: 'تحميل Pdf',
    watchVedio: 'مشاهده الفيديو',
    new: 'جديد',
    Learningprogress: 'جاري التعلم',
    Finished: 'منتهي',
    BankData: 'بيانات الحوالة البنكية',
    BankName: 'اسم البنك',
    AccName: 'رقم الحساب',
    BankNameTr: 'اسم البنك المحول له',
    AccNamer: 'اسم الحساب',
    Amountpaid: 'المبلغ المسدد',
    messageErr: 'اكتب شكواك',


    PhoneErr: 'يرجي كتابة رقم جوال صحيح',
    passwordErr: 'يرجي كتابه كلمة  مرور صحيحة',
    codeErre: 'يرجي كتابة كود التفعيل  صحيح',
    emailErr: 'يرجي كتابه بريد الكتروني صحيح',
    NotMatch: 'كلمة المرور غير متطابقة',
    usernameErr: 'يرجي كتابة الاسم بشكل صحيح',
    Cognitiveplans: 'الخطط الادراكية',
    Socialplans: 'الخطط الاجتماعة',
    NotifyApp: 'الأشعارات الخاصة بالتطبيق',
    AboutApp: 'كل ما يهم التطبيق',
    TermsCond: 'احكام وشروط خاصة بالتطبيق',
    RebQuestion: 'اسئلة تم تكرارها واجباتها',
    watchPlan: 'مشاهدة خطتي الفرديه',
    IBAN: 'رقم الايبان',
    CammeraErr: 'ليس لديك صلاحيات لدخول لمعرض الصور',
    chooseBank: 'اختر البنك ',
    resendCode: 'إعاده إرسال الكود'


}

export default ar