
const en = {
    lang: 'Language',
    arab: 'Arabic',
    next: 'Next',
    Login: 'Login',
    email: 'E-mail',
    password: 'Password',
    forgetPassword: 'Did you forget the password?',
    entry: 'Login',
    createAcc: 'Register now',
    haveAcc: 'You do not have an account?',
    phone: 'Phone',
    send: 'Send',
    RecoverPass: 'Password recovery',
    confirmPass: 'Confirm new password',
    NewPass: 'New password',
    confirm: 'Confirm',
    code: 'Validation code',
    Register: 'Register',
    name: 'Name',
    location: 'Location',
    CodeActive: 'Code activation',
    search: 'Search',
    HelloApp: 'Welcome to our educational application',
    FavLesson: 'Start your favorite lesson with us',
    lesson: 'Mylesson',
    Individualplans: 'Individual plans',
    hours: 'Hours',
    Lessons: 'Lesson',
    Rs: 'R.S',
    Cognitiveplans: 'Cognitive plans',
    Socialplans: 'Social plans',
    Home: 'Home',
    about: 'About application',
    Frequentlquestions: 'Frequently questions',
    Termsconditions: 'Terms and conditions',
    settings: 'Settings',
    Contact: 'Contact us',
    logout: 'Logout',
    notification: 'Notifications',
    NotifyApp: 'Notifications for the application',
    AboutApp: 'All that matters to the application',
    Firstitem: 'First item',
    seconTerm: 'Second item',
    TermsCond: 'Terms and conditions for the application',
    RebQuestion: 'Questions whose duties were repeated',
    SettApp: 'Settings for the application',
    changePass: 'Chnage password',
    NewPassword: 'New password',
    ContactAp: 'All platforms to communicate with the application',
    Social: 'Ways of communication',
    sochialMedia: 'Social Media',
    sendComplaint: 'Send a complaint',
    Subsections: 'Subsections',
    subscribe: 'Subscripe',
    PricePaln: 'Price plans',
    choosePlane: 'A package to participate in the total courses offered',
    Monthlyplans: 'Monthly plans',
    completeCours: 'Complete course',
    downloadPdf: 'Download Pdf',
    watchVedio: 'Watch Vedio',
    month: 'Month',
    Somthing: 'somthing went wrong',
    PlanErr: 'Please Choise paln',
    BankErr: 'Please Select Bank',
    BanknameErr: 'Please write bank name',
    AccountnameErr: 'Please write account name',
    AccountnNumberErr: 'Please write acouunt number',
    MoneyPaidErr: 'please write Mony Paid',
    BaseErr: 'Please insert Image',
    save: 'Save',
    throwPlan: 'The throw-out plan',
    yearPlan: 'Year plan',
    choosePay: 'Choose Way to Pay',
    Visa: 'Visa',
    Pay: 'Pay',
    messageErr: 'Write Complaiment',
    Transfermony: 'Bank transfer',
    payment: 'Payment',
    Confirmpayment: 'Confirm payment',
    paymentMony: 'The subscription to the monthly package was paid in an amount',
    bacjHome: 'Back home',
    myProfile: 'my Profile',
    new: 'New',
    Learningprogress: 'Learning in progress',
    Finished: 'Finished',
    watchPlan: 'Watch my Singles Plan',
    BankData: 'Bank transfer data',
    BankName: 'Bank name',
    AccName: 'Account Number',
    BankNameTr: 'The name of the transferring bank',
    AccNamer: 'Account name',
    Amountpaid: 'Amount paid',

    passwordErr: 'Please type a correct password',
    PhoneErr: 'Please type a correct phone number',
    codeErre: 'Please type a correct code activation ',
    emailErr: 'Please type a correct  E-mail ',
    NotMatch: 'Password not matching',
    usernameErr: 'Please type a correct name',

}
export default en